apiVersion: v1
kind: Service
metadata:
  name: app-nodeport
  labels:
    app: app-server
spec:
  type: NodePort
  selector:
    app: app-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
    name: http
