apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: network-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: data.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: data-internal
            port:
              number: 8080
  - host: api.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-clusterip
            port:
              number: 80
