apiVersion: v1
kind: Service
metadata:
  name: data-internal
  labels:
    app: data-server
spec:
  type: ClusterIP
  selector:
    app: data-server
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: http
